"""Lightweight local GoldBot-compatible backend for trading-agent testing."""

from __future__ import annotations

import threading
import uuid
from datetime import datetime, timezone
import re

from flask import Flask, jsonify, request

app = Flask(__name__)

_files: dict[str, dict] = {}
_simulations: dict[str, dict] = {}
_lock = threading.Lock()


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _make_report(file_content: str, query: str) -> str:
    text = file_content or ""
    match = re.search(r"5d Change Pct:\s*([-+]?\d+(?:\.\d+)?)", text, flags=re.IGNORECASE)
    change_pct = float(match.group(1)) if match else 0.0

    if change_pct > 0.1:
        direction = "BUY"
        confidence = 75
        tone = "bullish outlook with positive momentum and supportive sentiment"
    elif change_pct < -0.1:
        direction = "SELL"
        confidence = 75
        tone = "bearish outlook with downside pressure and elevated risk sentiment"
    else:
        direction = "HOLD"
        confidence = 55
        tone = "mixed market conditions with no clear directional edge"

    return (
        f"GoldBot local stub report.\n\n"
        f"Query: {query}\n\n"
        f"The current assessment suggests a {tone}. "
        f"Direction: {direction}. Confidence: {confidence}%.\n"
        f"This report was generated by the local compatibility backend for testing."
    )


@app.post("/api/upload")
def upload():
    payload = request.get_json(silent=True) or {}
    content = payload.get("content", "")
    file_id = f"file_{uuid.uuid4().hex[:12]}"
    with _lock:
        _files[file_id] = {"content": content, "created_at": _now()}
    return jsonify({"file_id": file_id})


@app.post("/api/simulate")
def simulate():
    payload = request.get_json(silent=True) or {}
    file_id = payload.get("file_id")
    query = payload.get("query", "")
    with _lock:
        file_record = _files.get(file_id, {})
        report_text = _make_report(file_record.get("content", ""), query)
        simulation_id = f"sim_{uuid.uuid4().hex[:12]}"
        _simulations[simulation_id] = {
            "status": "completed",
            "report_text": report_text,
            "created_at": _now(),
        }
    return jsonify({"simulation_id": simulation_id})


@app.get("/api/simulate/<simulation_id>/status")
def simulate_status(simulation_id: str):
    with _lock:
        simulation = _simulations.get(simulation_id)
    if not simulation:
        return jsonify({"status": "failed", "error": "simulation not found"}), 404
    return jsonify({"status": simulation["status"]})


@app.get("/api/simulate/<simulation_id>/report")
def simulate_report(simulation_id: str):
    with _lock:
        simulation = _simulations.get(simulation_id)
    if not simulation:
        return jsonify({"report_text": ""}), 404
    return jsonify({"report_text": simulation["report_text"]})


@app.get("/health")
def health():
    with _lock:
        return jsonify(
            {
                "status": "ok",
                "service": "goldbot-backend-stub",
                "files": len(_files),
                "simulations": len(_simulations),
            }
        )


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5001, debug=False)
